# 
# This workflow will build Javadocs for the various anchor Java projects aggregated together (but excluding the GUI).
#
# It is only triggered on master branch.
#
# It also:
#  -  uploads the built Javadoc in a JAR to GitHub Packages
#
# The Maven working directories are cached for future reuse, as downloading all packages from scratch takes significant time.
#
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
#

name: Generate aggregate Javadoc with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        
    steps:
    - uses: actions/checkout@v4
      with:
         submodules: true
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        server-id: central
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
        gpg-passphrase: GPG_PASSPHRASE

    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
      if: ${{ inputs.cache-sonar }}          

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-jdk${{inputs.os}}-rep
        restore-keys: ${{ runner.os }}-m2 
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn --batch-mode -f anchor-all/pom.xml site javadoc:aggregate
      
    - name: Deploy to GitHubPages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        branch: gh-pages
        folder: anchor-all/target/site/apidocs
        clean: true
        
    - name: Upload javadoc
      uses: actions/upload-artifact@v4
      with:
        name: anchor-javadoc-except-gui
        path: anchor-all/target/site/apidocs        
